# Generated by Django 4.2.6 on 2023-11-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_comision_curso_camada'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
